feat: add arb sepolia support
OffchainLabs/orbit-setup-script pull request #19
Opened 2023-09-06 16:58 UTC by gzeoneth

2023-09-06 17:37 UTC, mahsamoosavi requested changes

2023-09-06 17:37 UTC, mahsamoosavi commented on scripts/chargeEth.ts
> +  console.log('Transaction hash on Parent Chain: ', tx.hash)
In the interest of maintaining uniformity:
```suggestion
  console.log('Transaction hash on parent chain: ', tx.hash)
```

2023-09-06 17:37 UTC, mahsamoosavi commented on scripts/ethDeposit.ts
> +  console.log('Transaction hash on Parent Chain: ', tx.hash)
same:
```suggestion
  console.log('Transaction hash on parent chain: ', tx.hash)
```

2023-09-06 17:37 UTC, mahsamoosavi commented on scripts/setup.ts
> +      console.log('Funding batch-poster accounts on Parent Chain with 0.3 ETH')
```suggestion
      console.log('Funding batch-poster accounts on parent chain with 0.3 ETH')
```

2023-09-06 17:37 UTC, mahsamoosavi commented on scripts/setup.ts
> +      console.log(`Transaction hash on Parent Chain: ${tx1.hash}`)
```suggestion
      console.log(`Transaction hash on parent chain: ${tx1.hash}`)
```

2023-09-06 17:37 UTC, mahsamoosavi commented on scripts/setup.ts
> +        `Transaction was mined in block ${receipt1.blockNumber} on Parent Chain`
```suggestion
        `Transaction was mined in block ${receipt1.blockNumber} on parent chain`
```

2023-09-06 17:37 UTC, mahsamoosavi commented on scripts/setup.ts
> +      console.log('Funding staker accounts on Parent Chain with 0.3 ETH')
```suggestion
      console.log('Funding staker accounts on parent chain with 0.3 ETH')
```

2023-09-06 17:37 UTC, mahsamoosavi commented on scripts/setup.ts
> +      console.log(`Transaction hash on Parent Chain: ${tx2.hash}`)
```suggestion
      console.log(`Transaction hash on parent chain: ${tx2.hash}`)
```

2023-09-06 17:37 UTC, mahsamoosavi commented on scripts/setup.ts
> +        `Transaction was mined in block ${receipt2.blockNumber} on Parent Chain`
```suggestion
        `Transaction was mined in block ${receipt2.blockNumber} on parent chain`
```

2023-09-06 17:37 UTC, mahsamoosavi commented on scripts/setup.ts
> +        'Running ethDeposit Script to Deposit ETH from Parent Chain to your account on appchain ... 💰💰💰💰💰💰'
```suggestion
        'Running ethDeposit Script to Deposit ETH from parent chain to your account on appchain ... 💰💰💰💰💰💰'
```

2023-09-06 17:37 UTC, mahsamoosavi commented on scripts/setup.ts
> +      'Running tokenBridgeDeployment script to deploy token bridge contracts on Parent Chain and your appchain 🌉🌉🌉🌉🌉'
```suggestion
      'Running tokenBridgeDeployment script to deploy token bridge contracts on parent chain and your appchain 🌉🌉🌉🌉🌉'
```

2023-09-06 17:37 UTC, mahsamoosavi commented on scripts/tokenBridgeDeployment.ts
> +  console.log('initialising token bridge contracts on Parent Chain')
```suggestion
  console.log('initialising token bridge contracts on parent chain')
```

2023-09-06 17:37 UTC, mahsamoosavi commented on scripts/tokenBridgeDeployment.ts
> +  console.log('deploying token bridge contracts on Parent Chain')
```suggestion
  console.log('deploying token bridge contracts on parent chain')
```

2023-09-06 17:37 UTC, mahsamoosavi commented on scripts/tokenBridgeDeployment.ts
> +    `L2 Weth Gateway registered on Parent Chain with transaction hash: ${recep.transactionHash}`
```suggestion
    `L2 Weth Gateway registered on parent chain with transaction hash: ${recep.transactionHash}`
```

2023-09-06 17:37 UTC, mahsamoosavi commented on scripts/tokenBridgeDeployment.ts
> +  console.log('Token bridge contracts on Parent Chain 📇📇📇:')
```suggestion
  console.log('Token bridge contracts on parent chain 📇📇📇:')
```

2023-09-06 17:46 UTC, mahsamoosavi approved these changes
LGTM

2023-09-07 12:44 UTC, TucksonDev commented on scripts/tokenBridgeDeployment.ts
> +  const weth = rs.l2.weth
```suggestion
  const weth = rs.l2.weth
		? AeWETH__fac.attach(rs.l2.weth).connect(deployer)
		: await deployBehindProxy(deployer, AeWETH__fac, proxyAdmin.address)
	  rs.l2.weth = weth.address
```
(Adding potential missing code)
Should this try to deploy if the contract doesn't exist?

2023-09-07 12:47 UTC, TucksonDev commented on scripts/tokenBridgeDeployment.ts
Deployer complains on line 545 `[wethAddress]` because it hasn't been set.

If needed, we could get it from the l2 object above => `const wethAddress = l2.weth.address`

2023-09-08 14:15 UTC, Jason-Wanxt approved these changes
LGTM

2023-09-11 15:10 UTC, gzeoneth commented
@TucksonDev merge this if it works with your testing

2023-09-12 17:09 UTC, GreatSoshiant commented
LGTM!

2023-09-12 17:09 UTC, merged