feat: adding custom fee token support for orbit chains
OffchainLabs/orbit-setup-script pull request #26
Opened 2023-10-11 04:48 UTC by GreatSoshiant

In this PR we've added bunch of features to enable Orbit chains with custom fee tokens. Some of them here are:
1. erc20 token bridge deployment
2. Transfering native ERC20 token instead of ETH in ERC20 Path
3. adding a path to deposit more native token (similar to charging more ETH)

2023-10-11 06:45 UTC, Jason-W123 commented on scripts/setup.ts
>          const newBalance = await L3Provider.getBalance(config.chainOwner)
If it is erc20 deposit, here we should check erc20's balance?

2023-10-11 11:03 UTC, gzeoneth commented on toekn-bridge-contracts/AbsInboxMock.d.ts
These type files should not be included, it should import from the packages like this
https://github.com/OffchainLabs/orbit-setup-script/blob/a6159b0532f4fa39cb21a9e42385ce66d06e21ad/scripts/tokenBridgeDeployment.ts#L19-L20
Will ping when the relevant package is released later today.

2023-10-12 17:36 UTC, gzeoneth commented
Since https://github.com/OffchainLabs/token-bridge-contracts/releases/tag/v1.1.0-beta.1 is now released, we can use it instead of those type files.

2023-10-16 08:22 UTC, gvladika commented on scripts/createTokenBridge.ts
> +const TOKEN_BRIDGE_CREATOR_Arb_Goerli =
We can probably switch now to the "official" release - `0x17412CC654a49Cdd5cE6965359d190F100Cf24d9` is token bridge creator on ArbGoerli, and `0x0025E5A25D64e02Fa711cfAEdf83987dac917eaC` on ArbSepolia

2023-10-16 08:22 UTC, gvladika commented on scripts/chargeEthOrErc20.ts
> +    tx = await erc20Inbox.depositERC20(ethers.utils.parseEther(amount))
This will require native tokens to be approved earlier

2023-10-19 07:19 UTC, gzeoneth reviewed
Awesome, it looks much cleaner now. Some minor comment and some test to make sure both the ETH and ERC20 rollup setup works and we are good to go!

2023-10-19 07:19 UTC, gzeoneth commented on scripts/erc20TokenBridgeDeployment.ts
> +      ).connect(l2Provider).address
```suggestion
    : await l1TokenBridgeCreator.getCanonicalL2WethGatewayAddress(
          childChainId
        )
```

2023-10-19 07:19 UTC, gzeoneth commented on scripts/erc20TokenBridgeDeployment.ts
> +const L2WethGateway__factory = NamedFactoryInstance(L2WethGateway)
```suggestion
```

2023-10-20 03:14 UTC, gzeoneth approved these changes
LGTM, thanks @Jason-W123 for testing

2023-10-20 07:43 UTC, gvladika approved these changes

2023-10-20 11:12 UTC, gzeoneth requested changes
the token bridge creator lacked a getter for canonicalL2Multicall address
we also need a L1Multicall (not ArbMulticall) to be deployed on the parent chain
^^^ blockchain eng is working on fixing these

the setup script also lacked outputInfo.json which was previously generated by tokenBridgeDeployment.ts

2023-10-23 08:34 UTC, gvladika commented on scripts/erc20TokenBridgeDeployment.ts
> +  const l1MultiCall = await l1TokenBridgeCreator.l1MultiCall()
Typo in function name
```suggestion
  const l1MultiCall = await l1TokenBridgeCreator.l1Multicall()
```

2023-10-23 10:41 UTC, gzeoneth commented
Pre-release checklist:

- [ ] Merge https://github.com/OffchainLabs/orbit-setup-script/pull/30
- [ ] Test rollup deployment flow
- [ ] Test AnyTrust deployment flow
- [ ] Test custom fee token deployment flow
- [ ] Verify validator works in all deployment types
- [ ] Verify token bridge works in all deployment types
- [ ] Validate rollup ownership after setup
- [ ] Validate tokenbridge ownership after setup

2023-10-27 03:13 UTC, gzeoneth approved these changes

2023-10-27 03:33 UTC, merged