Transfer ownership to executor
OffchainLabs/orbit-setup-script pull request #30
Opened 2023-10-20 18:15 UTC by GreatSoshiant

In this PR we:
1. Remove the network.json file creation
2. Fix the outputInfo.json file 
3. Add a new script to transfer ownership from rollup owner address to upgrade executor on L3
4. Add the new script on 
5. Change and add new fields to runtime state management to be compatible with new scripts

2023-10-23 09:19 UTC, gvladika requested changes

2023-10-23 09:19 UTC, gvladika commented on scripts/transferOwnership.ts
> +    await l1TokenBridgeCreator.getCanonicalL2UpgradeExecutorAddress(l2ChainId)
l3ChainId should be provided instead of l2ChainId (every child chain has its own set of canonical addresses)

2023-10-23 09:19 UTC, gvladika commented on scripts/transferOwnership.ts
> +  '0x0025E5A25D64e02Fa711cfAEdf83987dac917eaC'
These addresses are out-of-date now. They are up to date in `createTokenBridge.ts` tho (`0x1C608642d0944e95957a7ac3a478EC17FA191E9A` and `0xC35800028e31044173d37291F425DCc42D068c84`). We should keep them in a single place, so it doesn't happen that we update in one place but forget to do it in another place

2023-10-23 10:36 UTC, gzeoneth commented on scripts/transferOwnership.ts
> +    await l1TokenBridgeCreator.getCanonicalL2UpgradeExecutorAddress(l2ChainId)
in general, the l1/l2/3 wordings are quite confusing in this repo. In certain places l1/l2 represent parent/child chain while at other times it is in their literal meanings. Understandably this is partially due to the wording adopted by the token bridge contracts but we should try to make it more clear in a future PR.

2023-10-23 13:41 UTC, gvladika commented on scripts/createTokenBridge.ts
> +        wethGateway: l2Network.tokenBridge.l1WethGateway,
l1WethGateway -> l2WethGateway

2023-10-23 19:14 UTC, GreatSoshiant commented on scripts/transferOwnership.ts
> +    await l1TokenBridgeCreator.getCanonicalL2UpgradeExecutorAddress(l2ChainId)
In most cases it's because of SDK wordings as Harry said. I'll try to change all of them that is possible

2023-10-24 07:35 UTC, gvladika approved these changes
lgtm

2023-10-24 10:48 UTC, merged